.TH "mpvc-web" "1" "September, 2026" "" ""
.hy
.SH NAME
.PP
mpvc-web \[en] Web application interface for mpvc control
.SH SYNOPSIS
.PP
mpvc-web [option]
.SH DESCRIPTION
.PP
\f[B]mpvc-web\f[R] is a lightweight web interface and HTTP API wrapper
for \f[C]mpvc\f[R].
It allows users to control an active local \f[C]mpv\f[R] media player
instance remotely over a network interface using standard HTTP methods
or a mobile-friendly browser interface.
.SH OPTIONS
.IP \[bu] 2
\f[C]-c\f[R] <start|stop|status> Set the mpvc-web HTTP server command.
This option is \f[B]required\f[R].
Accepted values are \f[C]start\f[R] to daemonize the server,
\f[C]stop\f[R] to terminate it, \f[C]status\f[R] to check is running.
.IP \[bu] 2
\f[C]-b\f[R]
.RS 2
.PP
Set the mpvc-web HTTP server bind address.
Defaults to \f[C]localhost\f[R].
.RE
.IP \[bu] 2
\f[C]-p\f[R] Set the mpvc-web HTTP server port.
Defaults to \f[C]8888\f[R].
.IP \[bu] 2
\f[C]-r\f[R]
.RS 2
.PP
Set the mpvc-web HTTP server root directory path.
Defaults to \f[C]/tmp/mpvc-web/root\f[R].
.RE
.IP \[bu] 2
\f[C]-R\f[R] Set the mpvc-web HTTP server HTML auto-refresh interval in
seconds.
Defaults to \f[C]240\f[R].
.IP \[bu] 2
\f[C]-s\f[R] Set the mpvc-web HTTP server SSL/TLS configurations or
certificate paths.
Defaults to empty.
.IP \[bu] 2
\f[C]-a\f[R] Set the mpvc-web HTTP server to include a
\f[C]ytdl-archive/\f[R] repository or path tracking download history.
Defaults to empty.
.IP \[bu] 2
\f[C]-h\f[R], \f[C]--help\f[R] Display the help synopsis and exit.
.SH EXAMPLES
.PP
Start the remote controller on all local interfaces using port 8888:
.IP
.nf
\f[C]
$ mpvc-web --host 0.0.0.0 --port 8888
\f[R]
.fi
.SH ENVIRONMENT
.IP \[bu] 2
\f[C]MPVC_SOCKET\f[R] The default path to the mpv IPC socket if the
\f[C]--socket\f[R] flag is omitted.
.IP \[bu] 2
\f[C]MPVC_WEB_PORT\f[R] Defines a default network port fallback if
\f[C]--port\f[R] is not explicitly set.
.SH FILES
.TP
\[ti]/.config/mpvc/mpvc.conf
mpvc configuration file.
.SH SEE ALSO
.IP \[bu] 2
\f[C]mpvc(1)\f[R]
.IP \[bu] 2
\f[C]mpvc-fzf(1)\f[R]
.IP \[bu] 2
\f[C]mpvc-tui(1)\f[R]
.IP \[bu] 2
\f[C]mpv(1)\f[R]
.SH AUTHOR
.PP
Manual written by gmt4.
See https://github.com/gmt4/mpvc for more information.
.SH REPORTING BUGS
.PP
Report bugs at: https://github.com/gmt4/mpvc/issues
