.\"
.TH "mpvc" "1" "April, 2026" "" ""
.hy
.SH NAME
.PP
mpvc - mpc-like command-line control interface for mpv
.SH SYNOPSIS
.IP
.nf
\f[C]
usage: mpvc opts # \[at]version v1.9 (c) gmt4 https://github.com/gmt4/mpvc
 -a | --add | add         : Add media to playlist (see --load for stdin).
 -r | --remove | rm       : Remove media by id from playlist (see searchrm for rm by title)
 -s | --stop | stop       : Always stop playback.
 -P | --play | play       : Always start playback.
 -p | --toggle            : Toggle playback.
      --repeat | repeat   : Loop the playlist.
      --single | single   : Loop a single file.
    | --next | next       : Jump to next entry in the playlist
    | --prev | prev       : Jump to previous entry in the playlist
 -i | --playlist          : Print filenames of tracks to fit within terminal.
 -I | --fullplaylist      : Print all filenames of tracks in current playlist.
 -v | --vol | vol         : Increase/decrease volume relative to current volume.
 -h | --help              : Prints the short help.
 -H | --help-long         : Prints the long help (tip: mpvc -H 2>&1 | less).

 -f | --format            : Enter a formatting string.
 -j | --track             : Go forwards/backwards through the playlist queue.
 -J | --tracknum          : Jump to playlist item number.
 -A | --playnext          : Add media to playlist after the current track.
 -n | --playnow           : Add media to playlist after the current track, and play it.
    | --playrand          : Select a random track from the playlist, and play it.
    | --save              : Save current playlist to given path.
    | --load              : Load playlist from given path (stdin if none is specified).
 -c | --crop              : Clear the playlist except for the media currently playing.
 -l | --loop              : Loop currently playing playlist.
 -L | --loopfile          : Loop currently playing file.
 -m | --mute              : Toggle sound.
 -t | --seek              : Increase/decrease playback time relatively, accepts % values.
    | --seekrand          : Set a random playback time.
 -T | --time              : Set absolute playback time.
 -x | --speed             : Increase/decrease speed relative to the current speed.
 -X | --speedval          : Set absolute speed.
 -z | --shuffle           : Toggle the shuffle property
 -I | --images            : Enable adding of images to the queue.
    | --color             : Enable color (NO_COLOR=)
    | --nocolor           : Disable color (NO_COLOR=true)
 -k | --kill              : Kill the mpv process controlling the given socket.
 -K | --killall           : Kill all mpv processes indiscriminately.
 -S | --socket            : Set mpv socket [default: $MPVC_SOCKET].
 -q | --quiet             : Suppress all text output.
 -V | --volume            : Set absolute volume.
 -Q | --vid=no            : Start mpv with video output disabled.
 -- |                     : After adding files options after -- are passed to mpv.
    | --version           : Prints the short version.
    | --version-long      : Prints the long version.

 (--)idleloop             : Listen to MPV events on $PROGNAME socket.
 (--)observe              : Observe property in MPV events on $PROGNAME socket.
 (--)playlist-shuffle     : Shuffle the current playlist
 (--)playlist-unshuffle   : Unshuffle the current playlist
 (--)search               : Search the playlist by filename/url.
 (--)searchplay|splay     : Search the playlist by filename and play the first match.
 (--)searchPlay|sPlay     : Search the playlist by title and play the first match.
 -R | --searchrm | srm    : Search the playlist and remove matching entries.
 -M | --searchmv | smv    : Search the playlist and move matching entries.

*tips: If unsure about where to begin, have a look at https://gmt4.github.io/mpvc
\f[R]
.fi
.SH DESCRIPTION
.PP
mpvc is a command-line utility that provides mpc-like control over the
mpv media player.
It allows users to manage playback, control volume, add and remove media
from the playlist, and display playlist information through a simple
command-line interface.
.PP
The tool communicates with mpv via a Unix socket, enabling remote
control of playback without direct interaction with the mpv window.
.SH OPTIONS
.SS Core Playback Commands
.TP
-P, --play, play
Always start playback.
.TP
-p, --toggle
Toggle playback.
.TP
-s, --stop, stop
Always stop playback.
.TP
--next, next
Jump to next entry in the playlist.
.TP
--prev, prev
Jump to previous entry in the playlist.
.TP
-j, --track
Go forwards/backwards through the playlist queue.
.TP
-J, --tracknum
Jump to playlist item number.
.SS Playlist Management
.TP
-a, --add, add
Add media to playlist (see --load for stdin).
.TP
-A, --playnext
Add media to playlist after the current track.
.TP
-n, --playnow
Add media to playlist after the current track, and play it.
.TP
--playrand
Select a random track from the playlist, and play it.
.TP
-r, --remove, rm
Remove media by id from playlist (see searchrm for rm by title).
.TP
-c, --crop
Clear the playlist except for the media currently playing.
.TP
--save
Save current playlist to given path.
.TP
--load
Load playlist from given path (stdin if none is specified).
.TP
--playlist-shuffle
Shuffle the current playlist.
.TP
--playlist-unshuffle
Unshuffle the current playlist.
.TP
-i, --playlist
Print filenames of tracks to fit within terminal.
.TP
-I, --fullplaylist
Print all filenames of tracks in current playlist.
.SS Advanced Search & Manipulation
.TP
--search
Search the playlist by filename/url.
.TP
--searchplay, splay
Search the playlist by filename and play the first match.
.TP
--searchPlay, sPlay
Search the playlist by title and play the first match.
.TP
-R, --searchrm, srm
Search the playlist and remove matching entries.
.TP
-M, --searchmv, smv
Search the playlist and move matching entries.
.SS Audio, Speed & Time Controls
.TP
-v, --vol, vol
Increase/decrease volume relative to current volume.
.TP
-V, --volume
Set absolute volume.
.TP
-m, --mute
Toggle sound.
.TP
-t, --seek
Increase/decrease playback time relatively, accepts % values.
.TP
--seekrand
Set a random playback time.
.TP
-T, --time
Set absolute playback time.
.TP
-x, --speed
Increase/decrease speed relative to the current speed.
.TP
-X, --speedval
Set absolute speed.
.SS Properties & Daemon Configuration
.TP
--repeat, repeat
Loop the playlist.
.TP
--single, single
Loop a single file.
.TP
-l, --loop
Loop currently playing playlist.
.TP
-L, --loopfile
Loop currently playing file.
.TP
-z, --shuffle
Toggle the shuffle property.
.TP
-I, --images
Enable adding of images to the queue.
.TP
--color
Enable color (NO_COLOR=).
.TP
--nocolor
Disable color (NO_COLOR=true).
.TP
-q, --quiet
Suppress all text output.
.TP
-Q, --vid=no
Start mpv with video output disabled.
.SS Events & Process Management
.TP
--idleloop
Listen to MPV events on $PROGNAME socket.
.TP
--observe
Observe property in MPV events on $PROGNAME socket.
.TP
-k, --kill
Kill the mpv process controlling the given socket.
.TP
-K, --killall
Kill all mpv processes indiscriminately.
.TP
-S, --socket
Set mpv socket [default: $MPVC_SOCKET].
.SS Help & Version Information
.TP
-f, --format
Enter a formatting string.
.TP
-h, --help
Prints the short help.
.TP
-H, --help-long
Prints the long help (tip: mpvc -H 2>&1, less).
.TP
--version
Prints the short version.
.TP
--version-long
Prints the long version.
.SH EXAMPLES
.PP
Add a file to the playlist:
.IP
.nf
\f[C]
mpvc -a /path/to/song.mp3
\f[R]
.fi
.PP
Toggle playback:
.IP
.nf
\f[C]
mpvc -p
\f[R]
.fi
.PP
Increase volume by 5:
.IP
.nf
\f[C]
mpvc -v +5
\f[R]
.fi
.PP
Decrease volume by 10:
.IP
.nf
\f[C]
mpvc -v -10
\f[R]
.fi
.PP
Display current playlist:
.IP
.nf
\f[C]
mpvc -i
\f[R]
.fi
.PP
Jump to next track:
.IP
.nf
\f[C]
mpvc --next
\f[R]
.fi
.PP
Stop playback:
.IP
.nf
\f[C]
mpvc -s
\f[R]
.fi
.PP
Enable repeat mode:
.IP
.nf
\f[C]
mpvc --repeat
\f[R]
.fi
.PP
Remove track with ID 3:
.IP
.nf
\f[C]
mpvc -r 3
\f[R]
.fi
.SH ENVIRONMENT
.TP
MPV_SOCKET
Path to the mpv Unix socket.
If not set, mpvc will attempt to locate the default socket
automatically.
.SH FILES
.TP
\[ti]/.config/mpv/mpv.conf
Main mpv configuration file.
.TP
\[ti]/.config/mpvc/mpvc.conf
mpvc-specific configuration file.
.TP
\[ti]/.config/mpvc/yt-dlp.conf
Configuration for yt-dlp integration.
.SH SEE ALSO
.PP
mpv(1), mpvc-fzf(1), mpvc-tui(1), mpvc-web(1), mpvc-equalizer(1),
mpvc-index,
.SH AUTHOR
.PP
Manual written by gmt4.
See <https://github.com/gmt4/mpvc> for more information.
.SH REPORTING BUGS
.PP
Report bugs at: <https://github.com/gmt4/mpvc/issues>
