#!/bin/sh
#
# @file mpvc-installer
# @version v1.0
# @description mpvc installer
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 MIT
# @url github.com/gmt4/mpvc
#

PROGNAME=$(basename "$0")
PROGVERSION="v1.0"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

PREFIX="${PREFIX:-/usr/local}"
BINDIR="${BINDIR:-$PREFIX/bin}"

SCRIPT="mpvc extras/mpvc-tui extras/mpvc-fzf extras/mpvc-chapter extras/mpvc-equalizer extras/mpvc-installer"

mpvc_fetch()
{
    mkdir -p "$BINDIR"
	for script in ${SCRIPT};
    do
        local="$BINDIR/$(basename "$script")"
        echo "Fetch $local"
        curl -fsSL -o "$local" "$PROGURL/raw/master/$script";
        chmod u+x "$local"
	done
}

mpvc_link()
{
    mkdir -p "$BINDIR"
	for script in ${SCRIPT};
    do
		ln -svfn "$(pwd)/$script" "$BINDIR";
	done
}

mpvc_install()
{
	echo 'Installing mpvc...'
    mkdir -p "$BINDIR"
	for script in ${SCRIPT};
    do
		install -Dvm755 "$(pwd)/$script" "$BINDIR";
	done
}

mpvc_uninstall()
{
	echo 'Un-installing mpvc...'
	for script in ${SCRIPT};
    do
        rm -v "$BINDIR/$(basename "$script")";
	done
}

usage()
{
    echo "usage: $PROGNAME args # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    echo "  fetch-user     : Fetch to BINDIR=$HOME/bin"
    echo "  link-user      : Symlink to BINDIR=$HOME/bin"
    echo "  install-user   : Install to BINDIR=$HOME/bin"
    echo "  install-sys    : Install to BINDIR=$PREFIX/bin"
    echo "  uninstall-sys  : Uninstall from BINDIR=$PREFIX/bin"
    echo "  uninstall-user : Uninstall from BINDIR=$HOME/bin}"
    echo "*tips: If unsure where to start, start with: $PROGNAME link-user"
    exit
}

main()
{
    [ $# -lt 1 ] && usage

    case "$1" in
    fetch-user)       shift; PREFIX=$HOME mpvc_fetch;;

    link-user)       shift; PREFIX=$HOME mpvc_link;;
    install-user)    shift; PREFIX=$HOME mpvc_install;;
    install-sys)     shift; PREFIX=/usr/local mpvc_install;;

    uninstall-user)  shift; PREFIX=$HOME mpvc_uninstall;;
    uninstall-sys)   shift; PREFIX=/usr/local mpvc_uninstall;;

    fetch)           shift; mpvc_fetch "$@";;
    link)            shift; mpvc_link "$@";;
    install)         shift; mpvc_install "$@";;
    uninstall)       shift; mpvc_uninstall "$@";;

    *) usage;;
    esac
}

main "$@"
