#!/usr/bin/env sh
#
# @file mpvc-now
# @description mpvc-now get a shareable URL to the "now listening" playlist
# @author gmt4 <gmt4 at github.com> (c) Copyright 2024 GPLv2+
# @url github.com/gmt4/mpvc
# SPDX-License-Identifier: GPL-2.0-or-later
#

PROGNAME=${0##*/}
PROGDIR=${0%/*}
PROGVERSION="v1.5"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

set -euf

mpvc() { "$PROGDIR/mpvc" "$@"; } # mpvc-web?

mpvcnow_geturls()
{
    mpvc saven
    #| sed -n "/^https/ ! s/^.*-\([0-9a-zA-Z_-]\{11\}\).opus/https:\/\/yewtu.be\/\1/p"
}

mpvcnow_getvids()
{
    vids=$( echo "$@" | awk '/youtube|yewtu/ {gsub("^.*/",""); gsub(".*=",""); print }' )

    for f in $vids;
    do
        echo -n "&v=$f";
    done
}

mpvcnow()
{
    date=$(date -Idate)
    now="https://gmt4.github.io/mpvc/now/"
    urls=$(mpvcnow_geturls)
    vids=$(mpvcnow_getvids "$urls")

    echo "$now?t=$date$vids"
    echo
    bash -c "paste <(echo \"$urls\") <(mpvc -I)"
}

mpvcnow1()
{
    mpvcnow "$@" | head -n1
}

usage()
{
    echo "usage: $PROGNAME [now] # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    exit;
}

main()
{
    [ -z "${1:-}" ] && usage

    case "${1:-}" in
    now)  mpvcnow "$@";;
    now1) mpvcnow1 "$@";;
    *) usage;;
    esac
}

main "$@"
