#!/bin/sh
#
# @file mpvc-equalizer
# @description mpvc equalizer based on firequalizer15.lua
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 MIT
# @url github.com/gmt4/mpvc
#

PROGNAME=$(basename "$0");
PROGVERSION="v1.0";
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

mpvc_genfilter()
{
    awk -v quote="'" -v gain_curr="$*" \
    '
    BEGIN {
      num_entry=15
      min_val = -360
      max_val = 120
 
      n=split("0  65 157 288 472 733 1k1 1k6 2k4 3k4 4k9 7k0 10k 14k 20k", freq_table)
      n=split("0   0   0   0   0   0   0   0   0   0   0   0   0   0   0", gain_table)
      if (gain_curr)
          n=split(gain_curr, gain_table)
    }

    function min(a,b) {return (a<b)?a:b;}
    function max(a,b) {return (a>b)?a:b;}
    function gen_gain_entry(gain_table)
    {
        str = ""
        for (x=1; x<=num_entry; x++)
        {
            v = min(max(gain_table[x], min_val), max_val)
            str = str sprintf("entry(%d,%.1f)", x-1, v)
            if (x < num_entry) str = str ";"
        }
        return str
    }
 
    function gen_filter(gain)
    {

        filter=\
        "firequalizer = "\
        "wfunc      = tukey:"\
        "delay      = 0.028:"\
        "scale      = linlog:"\
        "zero_phase = on:"\
        "gain_entry = "quote gain quote":"\
        "gain       = " quote "cubic_interpolate(2.8853900817779269*log(f/157.48+1))" quote
        return filter
    }
 
    END {
        gain_entry = gen_gain_entry(gain_table)
        gain_filter = gen_filter(gain_entry)
        print gain_filter
    }
  ' /dev/null
}

mpvc_values()
{
    mpvc getr af |
        jq '.data | .[] | .params.graph' |
        grep -o "gain_entry = '.*':" |
        sed -n 's/gain_entry = .//; s/.:$//; s|entry([0-9]\{1,2\},\([-.0-9]\+\));\?|\n\1 |gp'
}

mpvc_setvals()
{
    label="${label:-mpvc-equalizer}"
    filter=$(mpvc_genfilter "$*")
    mpvc cmdr af add "@$label:lavfi=[$filter]"
}

mpvc_bar_line()
{
    valf=$1
    min_val=-360
    val=$((${valf%%.*} - $min_val))
    x=10

    str=""
    while [ $x -le $val ]
    do
        str="${str}="
        x=$((x + 10))
    done
    echo "$str"
}

mpvc_bars()
{
    printf "# Linear Phase 15-Bands Equalizer\n"
    freq_table="0\n65\n157\n288\n472\n733\n1k1\n1k6\n2k4\n3k4\n4k9\n7k0\n10k\n14k\n20k\n"
    gain_table="$(mpvc_values | sed '/^$/d')"
    for i in $(seq 1 15)
    do
        f=$(echo "$freq_table" | awk -v i=$i 'NR==i')
        g=$(echo "$gain_table" | awk -v i=$i 'NR==i')
        bar=$(mpvc_bar_line $g)
        printf '%3s Hz: %6.1f dB %s\n' $f $g $bar
    done
}

mpvc_save()   { mpvc_vals; }
mpvc_load()   { mpvc_setvals "$(cat)"; }
mpvc_reset()  { mpvc_setvals "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"; }
mpvc_change() { mpvc_setvals $(mpvc_vals | sed "$@"); }
mpvc_vals()   { echo $(mpvc_values); }
mpvc_json()   { mpvc getr af | jq -C .data | sed '/graph/ s/:/:\n\t/g'; }

usage()
{
    echo "usage: $PROGNAME [save|load|reset] # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    exit;
}

main()
{
    [ $# -lt 1 ] && usage

    case "$1" in
    save)  mpvc_save;;
    load)  mpvc_load;;
    reset) mpvc_reset;;
    change) mpvc_change "$@";;
    values) mpvc_values;;
    vals)  mpvc_vals;;
    bars)  mpvc_bars;;
    json)  mpvc_json;;
    help)  usage;;
    esac
}

main "$@"
