#!/bin/sh
#
# @file mpvc-autostart
# @description mpvc auto pause/resume audio based on device presence
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 MIT
# @url github.com/gmt4/mpvc
#

PROGNAME=${0##*/}
PROGVERSION="v1.4"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

set -euf

# monitor the LAN IP of a device (eg your phone): so if device is present audio is resumed, otherwise, audio is paused.
mpvc_pingscan()
{
    [ $# -le 0 ] && exit
    target="$1"
    PERIOD=${PERIOD:-300}
    NCHECK=${NCHECK:-3}
    ncheck=0

    echo "# $PROGNAME mpvc pingscan PERIOD=$PERIOD NCHECK=$NCHECK $@"
    while sleep ${PERIOD}
    do
        hour=$(date +%_H)
        pause=$(mpvc -q get pause || true)
        check=$(ping -w 5 -c 5 $target | awk 'NR == 2 && /time=/ {print}')
        echo "# $(date -Imin) $PROGNAME PERIOD=$PERIOD NCHECK=$NCHECK pause=$pause c=${#check} n=${ncheck} $check"
        if [ "$hour" -ge 5 -a "$hour" -lt 20 ]
        then
            ncheck=$(( ( $ncheck $(if [ -n "$check" ]; then echo +; else echo -; fi) 1 ) % ( $NCHECK + 1 ) ))
            case "$ncheck" in
            $NCHECK|2|1) mpvc -q resume;; # +n pings up: resume
            -$NCHECK)    mpvc -q pause ;; # -n pings down: pause
            esac
            #[ "$ncheck" -eq "-$NCHECK" -a "$pause" = "true" ] && ncheck=0
        fi
    done
}

usage()
{
    echo "usage: $PROGNAME args # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    echo "example: $PROGNAME 192.168.0.2 # the LAN IP of your tablet/phone";
    exit;
}

main()
{
    [ $# -lt 1 ] && usage

    mpvc_pingscan "$@"
}

main "$@"
