#!/usr/bin/env sh
#
# @file mpvc-now
# @description mpvc-now get a shareable URL to the "now listening" playlist
# @author gmt4 <gmt4 at github.com> (c) Copyright 2024 GPLv2+
# @url github.com/gmt4/mpvc
#

set -euf

mpvcnow_geturls()
{
    mpvc saven
}

mpvcnow_getvids()
{
    vids=$(
        mpvcnow_geturls |
            awk '/youtube|yewtu/ {gsub("^.*/",""); gsub(".*=",""); print }'
    )

    for f in $vids;
    do
        echo -n "&v=$f";
    done
}

main()
{
    date=$(date -Idate)
    now="https://gmt4.github.io/mpvc/now/"
    vids=$(mpvcnow_getvids)
    urls=$(mpvcnow_geturls)

    echo "$now?t=$date$vids"

    bash -c "paste <(echo \"$urls\") <(mpvc -I)"
}

main "$@"
