#!/bin/sh
#
# @file mpvc-fzf
# @description mpvc fzf, mpv terminal user interface
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 MIT
# @url github.com/gmt4/mpvc
#

PROGNAME=$(basename "$0");
PROGVERSION=v1.0;
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

quiet()  { "$@" > /dev/null 2>&1; }
mpvctui_warn() { echo "$@" >&2; }

# Set defaults
mpvctui_defaults()
{
    MPVC_TERM=xterm
}

mpvctui_config()
{
    mpvctui_defaults
    if ! quiet command -v fzf; then
        mpvctui_warn "$PROGNAME: Warning: No fzf, Install to get fuzzy media search & play support!"
        sleep 1
    fi
    XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
    MPVC_CONFIG="${MPVC_CONFIG:-$XDG_CONFIG_HOME/mpvc/mpvc-tui.conf}"
    # if present load user config
    if [ -r "$MPVC_CONFIG" ];
    then
        . "$MPVC_CONFIG"
    fi
}

mpvctui_fzf_help="C-x:list C-v:yt-add C-\\:add C-o:play C-r:del C-t:reload C-s:seek C-spc:toggle"
mpvctui_fzf_preview()
{
    # fzf keys: ctrl + [dorstxv\]
    fzf \
        --ansi --reverse --no-sort \
        --multi \
        --bind='ctrl-space:execute-silent(mpvc toggle &)' \
        --bind='ctrl-o:execute-silent(mpvc play {n} &)' \
        --bind='ctrl-r:reload(mpvc fullplaylist)' \
        --bind='ctrl-s:execute-silent(mpvc seek +20 &)' \
        --bind='ctrl-t:execute-silent(mpvc remove {n} &)' \
        \
        --bind='ctrl-x:execute(mpvc-fzf -f {q})' \
        --bind='ctrl-v:execute(mpvc-fzf -p {q})' \
        --bind='ctrl-\:execute(mpvc-fzf -l)' \
        \
        --preview-window='up:5' \
        --preview="mpvc" \
        --header="$PROGNAME mpvc-fzf help: $mpvctui_fzf_help" \
        "$@"
        #--bind='ctrl-d:execute-silent(mpvc seek -20 &)' \
}

mpvctui_fzf_isearch()
{
    url_search="https://yewtu.be/search?q=$(for f in $@; do printf "%s+" "$f"; done)"

    echo "$url_search"
    curl -sL "$url_search&page=1" "$url_search&page=2" |
    awk '
        /^ *<p dir="auto">/ {
            gsub("^ *<p dir=\"auto\">",""); gsub("</p>",""); vtitle=$0
        }
        /<p class="video-data" dir="auto">/ {
            gsub("^ *<p class=\"video-data\" dir=\"auto\">",""); gsub(" views",""); gsub("</p>",""); shared=$0
        }
        /^ *<p class="length">/ {
            gsub("^ *<p class=\"length\">",""); gsub("</p>",""); vlength=$0
        }
        /^ *<a title="Audio mode/ {
            gsub("^ *<a title=\"Audio mode\" href=\"",""); gsub("\">","");
            gsub("/watch\\?v=", "https://youtu.be/"); gsub("&listen=1","");
            printf "%s %4s %7s %s\n", $0, shared, vlength, vtitle
        }'
}

mpvctui_fzf_iplay()
{
    mpvctui_fzf_isearch "$1" |
        mpvctui_fzf_preview --prompt="(youtube) " |
            awk '{print $1}'
}

mpvctui_fzf_local()
{
    find . -type f,d | sort |
        mpvctui_fzf_preview --prompt="(local) " |
            mpvc load
}

mpvctui_fzf_playlist()
{
    len=$(mpvc gets playlist-count)
    ( [ -z "$len" ] && echo || mpvc fullplaylist) |
        mpvctui_fzf_preview --prompt="(playlist) "
}

mpvctui_fzf_ddg()
{
    curl -A 'Mozilla/5.0' -sL "https://duckduckgo.com/html?q=$*&iax=videos&ia=videos" |
        awk  '
            function urldecode(url)
            {
                for (y=0; y < 127; y++)
                {
                    if (y != 37)
                        gsub(sprintf("%%%02x|%%%02X", y, y), y==38 ? "\\&" : sprintf("%c", y), url);
                    gsub(/%25/, "%", url);
                }
                return url
            }

            /result__a/ {
                gsub("<a rel=\"nofollow\" class=\"result__a\" href=\"//duckduckgo.com/l/\\?uddg=", "");
                gsub("&amp", "\\&");
                gsub("rut=[0-9a-f]+","");
                gsub("\">", " ");
                gsub("</a>","");

                gsub("%3A",":"); gsub("%2F","/"); gsub("%3F","?"); gsub("%3D","=");
                #print urldecode($0)
                print
            }'
}

mpvctui_ddg_play()
{
    mpvctui_fzf_ddg "$@" |
        mpvctui_fzf_preview |
            awk '{print $1}' | mpvc load
}

mpvctui_version()
{
    echo "usage: $PROGNAME -[$optflags] args # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
}

optflags="1d:DfFhs:p:P:lxv"
mpvctui_usage()
{
    echo "usage: $PROGNAME -[$optflags] args # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    echo "  -d : Set the WD to the media directory given as argument"
    echo "  -D : Search & play media using DuckDuckGo (fzf*)"
    echo "  -f : Start fzf to manage the current mpv playist (fzf*)"
    echo "  -l : Search & play local media (fzf*)"
    echo "  -s : Search for media using Invidious (fzf*)"
    echo "  -p : Search & play media found using Invidious (fzf*)"
    echo "  -x : Starts $PROGNAME in a new $MPVC_TERM (config \$MPVC_TERM) [combine -x with $optflags]"
    echo "*tips: If unsure about where to begin, start with: $PROGNAME -p kupla mirage"
    exit;
}

main()
{
    mpvctui_config
    [ $# -lt 1 ] && mpvctui_usage

    while getopts "$optflags" flag;
    do
        case "$flag" in
        1) shift; awk '{print $1}';;
        d) MPVC_DIR="$OPTARG"; cd "$MPVC_DIR" || return;;
        D) shift; mpvctui_ddg_play "$@";;
        #D) shift; mpvctui_fzf_ddg "$@";;
        f) shift; mpvctui_fzf_playlist ;;
        F) shift; mpvctui_fzf_preview "$@" ;;
        h) shift; mpvctui_usage ;;
        l) shift; mpvctui_fzf_local;;
        p) shift; mpvctui_fzf_iplay "$OPTARG" | mpvc load ;;
        P) shift; mpvctui_fzf_iplay "$OPTARG" | mpvc loadc ;;
        s) shift; mpvctui_fzf_isearch "$OPTARG";;
        x) shift; quiet command -v $MPVC_TERM && $MPVC_TERM -e "$0" "$@"; exit;;
        v) shift; mpvctui_version;;
        *) mpvctui_usage;;
        esac
    done
}

main "$@"
