#!/usr/bin/env sh
#
# @file mpvc-now
# @description mpvc-now get a shareable URL to the "now listening" playlist
# @author gmt4 <gmt4 at github.com> (c) Copyright 2024 GPLv2+
# @url github.com/gmt4/mpvc
# SPDX-License-Identifier: GPL-2.0-or-later
#

PROGNAME=${0##*/}
PROGDIR=${0%/*}
PROGVERSION="v1.5"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

set -euf

mpvc() { "$PROGDIR/mpvc" "$@"; } # mpvc-web?

mpvc_now_geturls() { mpvc saven; }
mpvc_now_getvids() { echo "$@" | awk '/youtube|yewtu/ { sub("^.*/",""); sub(".*=",""); sub("^","\\&v="); printf $0; }'; }

mpvc_now()
{
    date=$(date -Idate)
    now="https://gmt4.github.io/mpvc/now/"
    urls=$(mpvc_now_geturls)
    vids=$(mpvc_now_getvids "$urls")
    list=$(mpvc fullplaylist)

    echo "$now?t=$date$vids"
    echo
    awk -v u="$urls" -v l="$list" 'END{ split(u, au,"\n"); split(l, al,"\n"); for(u in au) {print au[u], al[u]}; }' /dev/null
}

mpvc_now1() { mpvcnow | head -n1; }

usage()
{
    echo "usage: $PROGNAME [now] # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    exit;
}

main()
{
    case "${1:-}" in
    now)  mpvc_now;;
    now1) mpvc_now1;;
    *)    usage;;
    esac
}

main "$@"
