#!/bin/sh
#
# @file mpvc-equalizer
# @description mpvc equalizer based on firequalizer15.lua
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 GPLv2+
# @url github.com/gmt4/mpvc
#

PROGNAME=${0##*/}
PROGVERSION="v1.5"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

MPVC_LABEL="${MPVC_LABEL:-mpvc-equalizer}"

set -euf

mpvc_genfilter()
{
    awk -v quote="'" -v gain_curr="$*" \
    '
    BEGIN {
      num_entry=15
      min_val = -360
      max_val = 120

      n=split("0  65 157 288 472 733 1k1 1k6 2k4 3k4 4k9 7k0 10k 14k 20k", freq_table)
      n=split("0   0   0   0   0   0   0   0   0   0   0   0   0   0   0", gain_table)
      if (gain_curr)
          n=split(gain_curr, gain_table)
    }

    function min(a,b) {return (a<b)?a:b;}
    function max(a,b) {return (a>b)?a:b;}
    function gen_gain_entry(gain_table)
    {
        str = ""
        for (x=1; x<=num_entry; x++)
        {
            v = min(max(gain_table[x], min_val), max_val)
            str = str sprintf("entry(%d,%.1f)", x-1, v)
            if (x < num_entry) str = str ";"
        }
        return str
    }

    function gen_filter(gain)
    {

        filter=\
        "firequalizer = "\
        "wfunc      = tukey:"\
        "delay      = 0.028:"\
        "scale      = linlog:"\
        "zero_phase = on:"\
        "gain_entry = "quote gain quote":"\
        "gain       = " quote "cubic_interpolate(2.8853900817779269*log(f/157.48+1))" quote
        return filter
    }

    END {
        gain_entry = gen_gain_entry(gain_table)
        gain_filter = gen_filter(gain_entry)
        print gain_filter
    }
  ' /dev/null
}

mpvc_presets()
{
    cmd=${1:-list}
    case "$cmd" in
    reset)      echo "0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0";;       # preset: Flat (Default)
    fullbass)   echo "4.8 5.7 5.7 3.3 1.0 -2.4 -4.8 -6.3 -6.7 -6.7";;  # preset: Full Bass
    fulltreble) echo "5.8 -5.8 -5.8 -2.4 1.4 6.7 9.6 9.6 9.6 10.1";;   # preset: Full Treble
    fullbastre) echo "4.3 3.3 0.0 -4.4 -2.9 1.0 4.8 6.7 7.2 7.2";;     # preset: Full Bass & Treble
    headphones) echo "2.8 6.7 3.3 -2.0 -1.4 1.0 2.8 5.7 7.7 8.6";;     # preset: Headphones
    largehall)  echo "6.2 6.2 3.3 3.3 0.0 -2.9 -2.9 -2.9 0.0 0.0";;    # preset: Large Hall
    live)       echo "2.9 0.0 2.4 3.3 3.3 3.3 2.4 1.4 1.4 1.4";;       # preset: Live
    party)      echo "4.3 4.3 0.0 0.0 0.0 0.0 0.0 0.0 4.3 4.3";;       # preset: Party
    soft)       echo "2.8 1.0 0.0 -1.4 0.0 2.4 4.8 5.7 6.7 7.2";;      # preset: Soft
    classical)  echo "0.0 0.0 0.0 0.0 0.0 -4.4 -4.4 -4.4 -5.8";;       # preset: Classical
    club)       echo "0.0 0.0 4.8 3.3 3.3 3.3 1.9 0.0 0.0";;           # preset: Club
    dance)      echo "5.7 4.3 1.4 0.0 0.0 -3.4 -4.4 -4.3 0.0 0.0";;    # preset: Dance
    pop)        echo "1.0 2.8 4.3 4.8 3.3 0.0 -1.4 -1.4 -1.0 -1.0";;   # preset: Pop
    reggae)     echo "0.0 0.0 0.0 -3.4 0.0 3.8 3.8 0.0 0.0 0.0";;      # preset: Reggae
    ska)        echo "1.4 -2.9 -2.4 0.0 2.4 3.3 5.3 5.7 6.7 5.8";;     # preset: Ska
    softrock)   echo "2.4 2.4 1.4 0.0 -2.4 -3.4 -2.0 0.0 1.4 5.3";;    # preset: Soft Rock
    rock)       echo "4.8 2.8 -3.4 -4.8 -2.0 2.4 5.3 6.7 6.7 6.7";;    # preset: Rock
    techno)     echo "4.8 3.3 0.0 -3.4 -2.9 0.0 4.8 5.7 5.8 5.3";;     # preset: Techno

    ''|help|list) grep '# preset: ' $0;;
    esac
}

mpvc_values()
{
    mpvc getr af |
        jq '.data | .[] | .params.graph' |
        grep -o "gain_entry = '.*':" |
        sed -n 's/gain_entry = .//; s/.:$//; s|entry([0-9]\{1,2\},\([-.0-9]\+\));\?|\n\1 |gp'
}

mpvc_setvals()
{
    filter=$(mpvc_genfilter "$*")
    mpvc cmdr af add "@$MPVC_LABEL:lavfi=[$filter]"
}

mpvc_bar_line()
{
    valf=$1
    min_val=-360
    max_val=770
    cols=${cols:-$(mpvc ttycols)}
    inc_val=$(( ( max_val - min_val ) / cols ))

    inc=${inc:-$inc_val}
    val=$((${valf%%.*} - min_val))
    x=${inc}

    str=""
    while [ "$x" -le $val ]
    do
        str="${str}="
        x=$((x + inc))
    done
    echo "$str"
}

mpvc_bars()
{
    mpvc_values="$(mpvc_values)"
    if [ -z "$mpvc_values" ]; then usage; fi
    freq_table="0\n65\n157\n288\n472\n733\n1k1\n1k6\n2k4\n3k4\n4k9\n7k0\n10k\n14k\n20k\n"
    gain_table="$(printf "$mpvc_values" | sed '/^$/d')"
    output="$(printf "# Linear Phase 15-Bands Equalizer\n")\n"

    for i in $(seq 1 15)
    do
        f=$(echo "$freq_table" | awk -v i=$i 'NR==i')
        g=$(echo "$gain_table" | awk -v i=$i 'NR==i')
        bar=$(mpvc_bar_line $g)
        output="$output$(printf '%3s Hz: %6.1f dB %s\n' $f $g $bar)\n"
    done
    printf "$output"
}

mpvc_save()   { mpvc_vals; }
mpvc_load()   { mpvc_setvals "$(cat)"; }
mpvc_reset()  { mpvc_setvals "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"; }
mpvc_clear()  { mpvc set af ""; }
mpvc_change() { mpvc_setvals $(mpvc_values | sed "$@"); }
mpvc_vals()   { echo "$(mpvc_values)"; }
mpvc_json()   { mpvc getr af | jq -C .data | sed '/graph/ s/:/:\n\t/g'; }

usage()
{
    echo "usage: $PROGNAME [save|load|reset|clear] # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    exit;
}

main()
{
    if [ $# -lt 1 ]; then usage; fi

    case "$1" in
    save)  mpvc_save;;
    load)  mpvc_load;;
    reset) mpvc_reset;;
    clear) mpvc_clear;;
    change) shift; mpvc_change "$@";;
    preset) shift; mpvc_presets "$@";;
    values) mpvc_values;;
    vals)  mpvc_vals;;
    bars)  mpvc_bars;;
    json)  mpvc_json;;

    help)  usage;;
    *)     usage;;
    esac
}

main "$@"
