#!/usr/bin/env sh
#
# @file mpvc-somafm
# @description mpvc-somafm, mpvc script for playing SomaFM channels
# @author gmt4 <gmt4 at github.com> (c) Copyright 2024 GPLv2+
# @url github.com/gmt4/mpvc
# SPDX-License-Identifier: GPL-2.0-or-later
#

file=${XDG_CONFIG_HOME:-$HOME/.config}/mpvc/somafm-channels.json
[ ! -s "$file" ] && curl -fsSL -o "https://somafm.com/channels.json"
jq -r '.channels | sort_by(.listeners | tonumber) | reverse | .[] | (.playlists[3]|.url) + ";" + .listeners + " ls "+.genre+";"+ .title' "$file" | column -s ';' -t | mpvc-fzf -F
