#!/usr/bin/env sh
#
# @file mpvc-web
# @description mpvc web, A hack to remotely control mpvc from web/http
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 MIT
# @url github.com/gmt4/mpvc
#

# REMEMBER This is a hack, DISCLAIMER * Use at Your Own Risk *
# A security hole in itself, with many open man-holes, evident ones are marked with XXX
#
# The sole reason for its existence is to mimic mpvc-tui when is not available,
# like, controlling a remotely running an mpv, accessing from a client without a CLI,
# like a laptop, tablet, or phone.

PROGNAME=${0##*/}
PROGVERSION="v1.4"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"
PROGINFO="A hack to remotely control mpvc from web # DISCLAIMER * Use at Your Own Risk *"

set -euf

mpvc_web_style()
{
    echo 'body { filter: invert(0.7); }'
}

mpvc_web_index()
{
    cat <<EOF
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="generator" content="gmt4 mpvc-web" />
    <meta name="author" content="gmt4 <gmt4 at github.com> (c) Copyright 2022" />
    <meta name="description" content="mpvc-web, a mpvc-tui for the web" />

    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
    <meta http-equiv="Content-Type" content="text/html">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="pragma" content="no-cache" />
    $(if [ -n "${MPVC_WEB_REFRESH:-}" ]; then echo "<meta http-equiv=refresh content=$MPVC_WEB_REFRESH>"; fi)
    <link rel="IconFile" href="apple-touch-icon.svg" sizes="64x64">
    <link rel="apple-touch-icon" href="apple-touch-icon.svg">
    <title>$PROGNAME @ $MPVC_WEB_HOSTNAME 🎧</title>
    </head>
    <style type="text/css" media="all">
    :root { --body-bg: #fff; --body-color: #111; --pre-bg:#eee; --link-color:#00f; } /* Light mode */
    @media (prefers-color-scheme: dark) {
       :root { --body-bg: #222; --body-color: #eee; --pre-bg:#333; --link-color:#07f; } /* Dark mode */
    }
    body { background: var(--body-bg); color: var(--body-color); font-family: monospace; }
    code { background: var(--pre-bg); }
    pre  { background: var(--pre-bg); }
    a    { color: var(--link-color); padding: 0.05rem 0.05rem; }
    </style>
    <link rel="stylesheet" href="style.css" />

    <body>
        [ <a href="." name="mpvc-web">$PROGNAME</a> ] <hr>
        <ul style="padding: 0em 1em;">
        <li>
        <!-- enable this optionally: only for dev/testing -->
        <form action="/" method="get">
            mpvc cli
            <input type="text" id="cli" name="cli" placeholder="mpvc status ${MPVC_WEB_DEV:-(off)}" title="mpvc cli" onkeydown="if (event.keyCode == 13) { this.form.submit(); return false; }">
        </form>
        <li>
            <form action="/" method="get">
            mpvc stash
            $(mpvc stash list | awk '
                BEGIN   { printf "<select name=cli id=cli-select onchange=this.form.submit() style=\"width:11rem\">"}
                NR == 1 { printf "<option value="">Please choose a stash</option>" }
                NR > 1  { printf "<option value=\"mpvc stash apply "$NF"\">"$NF"</option>" }
                END     { printf "</select>"}' )
            </form>
        </li>
        </li>
        <li>
            mpvc
            <a href="?cmd=mpvc status">status</a>
            <a href="?cmd=mpvc toggle">toggle</a>
            <a href="?cmd=mpvc mpv">mpv</a>
            <a href="?cmd=mpvc kill">kill</a>
            <a href="?cmd=mpvc clear">clear</a>
        </li>
        <li>
            mpvc
            <a href="?cmd=mpvc play">play</a>
            <a href="?cmd=mpvc start 0">start</a>
            <a href="?cmd=mpvc start $">end</a>
            <a href="?cmd=mpvc stop">stop</a>
            <a href="?cmd=mpvc prev">prev</a>
            <a href="?cmd=mpvc next">next</a>
        </li>
        <li>
            mpvc
            <a href="?cmd=mpvc repeat">repeat</a>
            <a href="?cmd=mpvc single">single</a>
            <a href="?cmd=mpvc cmd ab-loop">ab-loop</a>
        </li>
        <li>
            mpvc
            <a href="?cmd=mpvc playlist-shuffle">playlist</a>
            <a href="?cmd=mpvc shuffle">shuffle</a>
            <a href="?cmd=mpvc unshuffle">unshuffle</a>
        </li>
        <li>
            mpvc ch
            <a href="?cmd=mpvc cstart">cstart</a>
            <a href="?cmd=mpvc creplay">creplay</a>
            <a href="?cmd=mpvc cprev">cprev</a>
            <a href="?cmd=mpvc cnext">cnext</a>
        </li>
        <li>
            mpvc vol
            <a href="?cmd=mpvc vol -20">-20</a>
            <a href="?cmd=mpvc vol -10">-10</a>
            <a href="?cmd=mpvc vol -5">-5</a>
            <a href="?cmd=mpvc vol 0">0</a>
            <a href="?cmd=mpvc vol +5">+5</a>
            <a href="?cmd=mpvc vol +10">+10</a>
            <a href="?cmd=mpvc vol +20">+20</a>
        </li>
        <li>
        theme
            <a href="#" title="theme 0" onclick="document.body.style.WebkitFilter='invert(0)';">th0</a> |
            <a href="#" title="theme 4" onclick="document.body.style.WebkitFilter='invert(0.4)';">th4</a> |
            <a href="#" title="theme 6" onclick="document.body.style.WebkitFilter='invert(0.6)';">th6</a> |
            <a href="#" title="theme 8" onclick="document.body.style.WebkitFilter='invert(0.8)';">th8</a> |
            <a href="." title="reset">rst</a>
        </li>
<!--
        <li>
            mpvc
            <a href="?cmd=mpvc stop" title="mpvc stop" >⏹️</a>
            <a href="?cmd=mpvc play" title="mpvc play">▶️</a>
            <a href="?cmd=mpvc toggle" title="mpvc toggle">⏸️</a> |
            <a href="?cmd=mpvc seek -60" title="mpvc seek-60">⏪</a>
            <a href="?cmd=mpvc seek +60" title="mpvc seek+60">⏩</a> |
            <a href="?cmd=mpvc prev" title="mpvc prev">⏮️</a>
            <a href="?cmd=mpvc next" title="mpvc next">⏭️</a> |
            <a href="?cmd=mpvc single" title="mpvc single">🔄</a>
        </li>
-->
        </ul>
        [ <a href="#mpvc-web-status" name="mpvc-web-status">Status</a> ] <hr>
        <iframe name="mpvc-status" width="100%" height="100%" frameborder="0" src="/cgi-bin/mpvc?status" allowtransparency="true" ></iframe>
        [ <a href="#mpvc-web-playlist" name="mpvc-web-playlist">Playlist</a> <a href="#mpvc-web-fullplaylist" name="mpvc-web-fullplaylist">full</a> <a href="#mpvc-web-rawplaylist" name="mpvc-web-rawplaylist">raw</a> <a href="#mpvc-web-chapterlist" name="mpvc-web-chapterlist">chapters</a> <a href="." >clear</a> ] <hr>
        <div style="display:flex">
        <iframe name="mpvc-playlist" width="100%" frameborder="0" src="/cgi-bin/mpvc?playlist" allowtransparency="true" style="margin:auto" ></iframe>
        <script>
        var playlist = document.getElementsByName('mpvc-playlist')[0];
        switch (window.location.hash)
        {
            case '#mpvc-web-playlist':      { playlist.src='/cgi-bin/mpvc?playlist'; break; }
            case '#mpvc-web-fullplaylist':  { playlist.src='/cgi-bin/mpvc?fullplaylist'; break; }
            case '#mpvc-web-rawplaylist':   { playlist.src='/cgi-bin/mpvc?rawplaylist'; break; }
            case '#mpvc-web-chapterlist':   { playlist.src='/cgi-bin/mpvc?chapterlist'; break; }
        }
        </script>
        </div>
        [ <a href="#mpvc-web-prompt" name="mpvc-web-prompt">Prompt</a> ] <hr>
        🎧 <a href="$PROGURL">$PROGNAME</a> $PROGVERSION, mpvc-tui for the web
    </body>
</html>
EOF
}

mpvc_web_cgi()
{
    MPVC=$(command -v mpvc)
    cat <<EOF
#!/bin/sh
set -euf
mpvc_strip_escapes(){ sed '/\x1b\[7m/ { s|\x1b\[7m||; s| |+|; }; s|\x1b\[0m||;'; }
main()
{
    if [ -n "\${USER:-}" ]; then
        env -i PATH="/usr/bin:/bin" HOME="\$HOME" TERM="\$TERM" QUERY_STRING="\${QUERY_STRING:-}" "\$0" "\$@"; exit;
    fi
    echo "Content-Type: text/plain"
    echo
    case "\${QUERY_STRING:-}" in
        status)       $MPVC status;;
        playlist)     $MPVC playlist | mpvc_strip_escapes ;;
        fullplaylist) $MPVC fullplaylist | mpvc_strip_escapes ;;
        rawplaylist)  $MPVC saven | mpvc_strip_escapes ;;
        chapterlist)  $MPVC chapter-list | mpvc_strip_escapes ;;
        *) $MPVC ;;
    esac
}
main "\$@"
EOF
}

mpvc_web_favicon()
{
    cat <<EOF
<svg viewBox="0 0 192 80" xmlns="http://www.w3.org/2000/svg" > <text x="0" y="30" font-size="45px" >🎧</text> </svg> <!-- mpvc -->
EOF
}

mpvc_web_stunnel_cfg()
{
    cat <<EOF
# stunnel.cfg for $PROGNAME $PROGVERSION $PROGURL
sslVersion = all
options = NO_SSLv2
options = NO_SSLv3

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
pid=$MPVC_WEB_SSL_PID

[mpvc-web]
accept = $MPVC_WEB_HOST:$MPVC_WEB_SSL_PORT
connect = $MPVC_WEB_HOST:$MPVC_WEB_PORT

cert = ${MPVC_WEB_SSL_PEM}
key  = ${MPVC_WEB_SSL_PEM}
cafile = ${MPVC_WEB_SSL_PEM}
verify=$MPVC_WEB_SSL_VERIFY
TIMEOUTclose = 0
EOF
}

mpvc_web()
{
    MPVC_WEB_HOST=${MPVC_WEB_HOST:-localhost}
    MPVC_WEB_PORT=${MPVC_WEB_PORT:-8000}
    MPVC_WEB_ROOT=${MPVC_WEB_ROOT:-/tmp/mpvc-web/root}
    MPVC_WEB_HOSTNAME=$(hostname)
    MPVC_WEB_SSL_PORT=${MPVC_WEB_SSL_PORT:-8443}
    MPVC_WEB_SSL_PEM=$MPVC_WEB_ROOT/../stunnel.pem
    MPVC_WEB_SSL_CFG=$MPVC_WEB_ROOT/../stunnel.cfg
    MPVC_WEB_SSL_PID=$MPVC_WEB_ROOT/../stunnel.pid
    MPVC_WEB_SSL_ENABLE=${MPVC_WEB_SSL_ENABLE:-}
    MPVC_WEB_SSL_VERIFY=${MPVC_WEB_SSL_VERIFY:-0}
    echo "# $PROGNAME $PROGVERSION running (beta version: might contain bugs!)"

    if ! command -v python3 >/dev/null; then
        echo "$PROGNAME: Error: No python3 found, install to continue."
        exit
    fi

    (
        # setup http webroot
        chmod u+w -R "${MPVC_WEB_ROOT%/*}"
        mkdir -p "$MPVC_WEB_ROOT" || return
        mkdir -p "$MPVC_WEB_ROOT/cgi-bin/" || return
        cd "$MPVC_WEB_ROOT" || return

        mpvc_web_index > "$MPVC_WEB_ROOT/index.html"
        mpvc_web_favicon > "$MPVC_WEB_ROOT/apple-touch-icon.svg"
        [ ! -e "$MPVC_WEB_ROOT/style.css" ] && mpvc_web_style > "$MPVC_WEB_ROOT/style.css"
        mpvc_web_cgi > "$MPVC_WEB_ROOT/cgi-bin/mpvc"
        chmod u+x "$MPVC_WEB_ROOT/cgi-bin/mpvc"

        # setup https stunnel if requested
        if [ -n "${MPVC_WEB_SSL_ENABLE:-}" ]; then
            echo "# Serving HTTPS on https://$MPVC_WEB_HOST:$MPVC_WEB_SSL_PORT"
            mpvc_web_stunnel_cfg > "$MPVC_WEB_SSL_CFG"
            if [ ! -e "$MPVC_WEB_SSL_PEM" ]; then
                MPVC_WEB_SSL_SUBJ="/C=CN/ST=ST/O=$PROGNAME/CN=$PROGNAME-$MPVC_WEB_HOSTNAME"
                openssl req -new -x509 -days 365 -nodes -out "$MPVC_WEB_SSL_PEM" -keyout "$MPVC_WEB_SSL_PEM" -subj "$MPVC_WEB_SSL_SUBJ"
                openssl pkcs12 -export -passout "pass:" -in "$MPVC_WEB_SSL_PEM" -out "$MPVC_WEB_SSL_PEM.p12"
            fi
            if [ -e "$MPVC_WEB_SSL_PID" ]; then
                kill "$(cat "$MPVC_WEB_SSL_PID")" || true
            fi
            stunnel "$MPVC_WEB_SSL_CFG"
        fi
        chmod a-w -R "$MPVC_WEB_ROOT/"

        # XXX handle cli commands, rewrite this mess
        python3 -u -m http.server --cgi --bind "$MPVC_WEB_HOST" "$MPVC_WEB_PORT" "$@" 2>&1 | awk \
        '
        /GET \/\?cmd=mpvc%20mpv/          { system("mpvc -q mpv") }
        /GET \/\?cmd=mpvc%20clear/        { system("mpvc -q clear") }
        /GET \/\?cmd=mpvc%20kill/         { system("mpvc -q kill") }

        /GET \/\?cmd=mpvc%20toggle/       { system("mpvc -q toggle") }
        /GET \/\?cmd=mpvc%20play/         { system("mpvc -q play") }
        /GET \/\?cmd=mpvc%20start%200/    { system("mpvc -q start 0") }
        /GET \/\?cmd=mpvc%20start%20$/    { system("mpvc -q start $") }
        /GET \/\?cmd=mpvc%20stop/         { system("mpvc -q stop") }
        /GET \/\?cmd=mpvc%20prev/         { system("mpvc -q prev") }
        /GET \/\?cmd=mpvc%20next/         { system("mpvc -q next") }

        /GET \/\?cmd=mpvc%20shuffle/      { system("mpvc -q shuffle") }
        /GET \/\?cmd=mpvc%20unshuffle/    { system("mpvc -q unshuffle") }

        /GET \/\?cmd=mpvc%20vol%20.*/     { gsub("%20", " "); system("mpvc -q vol "$(NF-3)); }

        /GET \/\?cmd=mpvc%20repeat/       { system("mpvc -q repeat") }
        /GET \/\?cmd=mpvc%20single/       { system("mpvc -q single") }

        /GET \/\?cmd=mpvc%20cstart/       { system("mpvc -q cplay 0") }
        /GET \/\?cmd=mpvc%20creplay/      { system("mpvc -q chapter-replay") }
        /GET \/\?cmd=mpvc%20cprev/        { system("mpvc -q chapter-prev") }
        /GET \/\?cmd=mpvc%20cnext/        { system("mpvc -q chapter-next") }

        /GET \/\?cli=mpvc/                {
            r=$0;
            gsub("HTTP.*$", "", r);
            gsub("^.*GET \\/\\?cli=mpvc\\+", "mpvc ", r);

            if (ENVIRON["MPVC_WEB_DEV"] && match(r, "^mpvc"))
            {
                gsub("(mpvc) [^a-zA-Z0-9 ]", "", r);
                gsub("\\+", " ", r);
                system(r); # XXX
            }
        }

        { print $0 }
        '
    )
}

usage()
{
    echo "usage: $PROGNAME 8000 # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL"
    exit
}

main()
{
    [ $# -lt 0 ] && usage

    mpvc_web "$@"
}

main "$@"
